# Activate: SPRING_PROFILES_ACTIVE=...,vault
spring:
  cloud:
    vault:
      enabled: ${VAULT_ENABLED:true}
      uri: ${VAULT_URI:http://localhost:8200}
      authentication: ${VAULT_AUTHENTICATION:TOKEN}
      token: ${VAULT_TOKEN:root}
      fail-fast: false
      kv:
        enabled: true
        backend: secret
        default-context: paymentprocessor/payment-service
  config:
    import: "optional:vault://"
