apiVersion: v2
name: payment-service
description: Payment orchestration service
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - payment
  - payment-processor
  - spring-boot
maintainers:
  - name: payment-processor
