apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "payment-service.fullname" . }}-config
  labels:
    {{- include "payment-service.labels" . | nindent 4 }}
data:
  SPRING_APPLICATION_NAME: {{ .Values.config.SPRING_APPLICATION_NAME | quote }}
  SERVER_PORT: {{ .Values.config.SERVER_PORT | quote }}
  TRACING_SAMPLING_PROBABILITY: {{ .Values.env.TRACING_SAMPLING_PROBABILITY | quote }}
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: {{ .Values.env.MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE | quote }}
  DB_URL: {{ .Values.config.DB_URL | quote }}
  DB_USERNAME: {{ .Values.config.DB_USERNAME | quote }}
  DB_USER: {{ .Values.config.DB_USER | quote }}
