apiVersion: v1
kind: Namespace
metadata:
  name: payment-processor
  labels:
    app.kubernetes.io/part-of: payment-processor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentprocessor
  namespace: payment-processor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: payment-processor
data:
  KAFKA_BOOTSTRAP: "kafka:9092"
  VAULT_URI: "http://vault.payment-processor.svc.cluster.local:8200"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.payment-processor.svc.cluster.local:4318/v1/traces"
  TRACING_SAMPLING_PROBABILITY: "0.1"
  CONFIG_SERVER_URL: "http://config-server:8888"
